### ISSUE TITLE
Multiple Front Ends causes issue adding to cart 

### ISSUE THREAD

**Issue by idcrosby** [microservices-demo/microservices-demo#245] opened 2016-08-12 08:40 UTC
Need to reproduce this locally first (was seen by Adam running custom setup on kubernetes)

**Comment by nustiueudinastea** [comment] 2017-01-05 12:01
I reproduced this bug for the kubernetes on minikube setup. It can be reproduced by deploying Sock Shop on minikube and than increasing the numbers of replicas for the front-end deployment:

kubectl --namespace sock-shop scale --replicas=3 deployment/front-end

Still investigating why this is happening.

**Comment by nustiueudinastea** [comment] 2017-01-05 15:31
The bug was caused by having client requests being forwarded round-robin over each font-end replica. At that point express.js session module (node.js) would create a new session, which meant that you would never get to see the cart with any items inside of it. There are 2 ways to fix this:
1. Share session data across the node.js instances. 
2. Have session affinity at the k8s service level. 

K8s offeres the option to apply session affinity for a service, which is easier than sharing session data, so I used that.

**Comment by nustiueudinastea** [comment] 2017-01-05 15:32
Fixed by https://github.com/microservices-demo/microservices-demo/pull/514

**Closed as completed by nustiueudinastea** 2017-01-05 15:32 UTC
Labels: bug, architecture

**Comment by rade** [comment] 2017-01-05 15:33
The implication is that a single node outage will lose all the shopping carts for sessions that were "connected" to that node.

**Comment by nustiueudinastea** [comment] 2017-01-05 15:41
Indeed. This might be improved by changing the way the session module generates the session id, so it relies on a client cookie. As far as I understand the cart service saves the user cart to a db, which means that a user cookie could be used to identify the user and retrieve it from the db.  

The other way to do it is to have the sessions backed by a database, but I suspect this is quite a bit of work.

**Comment by nustiueudinastea** [comment] 2017-01-05 15:43
BTW, if a user is logged in, the user doesn't loose it's cart if a node goes down. That only happens if a user is not logged in.
