### ISSUE TITLE
Rename manifests for carts

### ISSUE THREAD

**Issue by jasonrichardsmith** [microservices-demo/microservices-demo#729] opened 2017-07-11 14:55 UTC
When the manifests for carts/carts-db were updated to the new name the actual manifest filenames were not updated.
https://github.com/microservices-demo/microservices-demo/commit/9bc21263bae28b0278ac5361c6cb744916cc8803

move cart.yaml to carts.yaml, etc.

**Comment by dothanhhai** [comment] 2017-07-27 03:36
The cart service doesn't work when deploy on kubenetes (when access to /cart)
`{
"timestamp" : 1501124515797,
"status" : 500,
"error" : Internal Server Error,
"exception" : org.springframework.dao.DataAccessResourceFailureException,
"message" : Timed out after 10000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=carts-db:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: carts-db}, caused by {java.net.UnknownHostException: carts-db}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 10000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=carts-db:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: carts-db}, caused by {java.net.UnknownHostException: carts-db}}],
"path" : /carts/Vlb1NqbPQQYxHXOoHJLxQ5x9vKPqxfuF/items
}`

**Comment by embs** [comment] 2017-08-08 14:25
Possibly related to #717, as per this comment: https://github.com/microservices-demo/microservices-demo/issues/717#issuecomment-308067148

**Comment by pidster** [comment] 2017-12-12 10:51
I think this was fixed in #730

**Closed as completed by pidster** 2017-12-12 10:51 UTC
