### ISSUE TITLE
Try using `ecs compose`

### ISSUE THREAD

**Issue by errordeveloper** [microservices-demo/microservices-demo#144] opened 2016-07-19 10:43 UTC
Since https://github.com/aws/amazon-ecs-cli/issues/13 `ecs compose` is supposed to be usable with any `docker-compose.yml` file, so may be we could make things easier for the user and simplify some of our code. Not sure if v2 syntax is supported yet...

**Comment by nustiueudinastea** [comment] 2016-12-15 13:23
This is a duplicate of https://github.com/microservices-demo/microservices-demo/issues/455. Closing

**Closed as completed by nustiueudinastea** 2016-12-15 13:23 UTC
