### ISSUE TITLE
lack of connectivity, even when running load tests

### ISSUE THREAD

**Issue by rade** [microservices-demo/microservices-demo#443] opened 2016-12-05 13:30 UTC
Even when running the load test, Weave Scope often does not show all the expected connections between all the SockShop components/services.

**Comment by nustiueudinastea** [comment] 2017-01-06 12:05
Hi @rade , I have been trying to reproduce this problem using the Docker Compose + Weave deployment and Scope detects all the connections for me. It is dynamic and changes depending on what's happening at the moment but when I run the load tests, it seems that Scope detects all the connections correctly.

Are there any other details that might be relevant? How did you deploy Sock Shop?

![weave_sock_shop](https://cloud.githubusercontent.com/assets/588327/21717357/1870a98e-d419-11e6-99f0-9acbcd3e97d2.png)

**Comment by rade** [comment] 2017-01-06 12:12
I was using some k8s and ECS based deployments, hooked up to Weave Cloud, when demoing sock-shop at re:invent. I think @pidster set up the deployments and ran into this problem too. He may be able to offer some instructions on re-creating the deployments.

**Comment by nustiueudinastea** [comment] 2017-01-06 12:14
Ok, in the mean time, I can test this with Weave cloud, because I only tested it locally.

**Comment by rade** [comment] 2017-01-06 12:17
right. and next step would be to test with k8s-on-aws and ecs, both against Weave Cloud, since that is what we had running at re:invent. Alas I don't remember instance types, number of VMs, etc; am hoping @pidster does.

**Comment by pidster** [comment] 2017-01-06 14:00
I've typically used 3 or 4x m4.large.

**Comment by nustiueudinastea** [comment] 2017-01-06 16:38
@pidster @rade the k8s instructions use the same AWS instance sizes (m4.large), with the exception of the k8s master, which uses a m4.medium.

I ran various tests and indeed there is something weird going on, but I am not sure it's a problem with Weave Scope or the agents.

- when I run the load tests, I missing two expected connections: connections to payment and shipping services
- when I manually navigate on the website and add a a product to the cart and checkout, the payment and shipping connections show up in Weave Scope.

The following is a screen shot with Scope showing all the connections.
![screen shot 2017-01-06 at 18 28 51](https://cloud.githubusercontent.com/assets/588327/21724872/afd17824-d43e-11e6-8874-2c5713853b69.png)

**Comment by rade** [comment] 2017-01-06 16:46
I kinda assumed this was a problem with the load test or the sock shop k8s setup. Would be great if you ascertained whether that is the case, or the problem is in Scope.

**Comment by nustiueudinastea** [comment] 2017-01-06 16:49
I don't think it's Scope but I will continue troubleshooting this Monday morning to find out what exactly is causing it.

**Comment by nustiueudinastea** [comment] 2017-01-09 16:58
I tracked down the problem to a bug that was caused by the front-end service. When the load-test runs, it creates a new user, address and credit card. The address and the credit card are supposed to be associated with the user, but because of this bug, they weren't. This lead to orders being posted with a username that doesn't have an address and a credit card, which in turn lead to an early termination of the order flow. The payment and the shipping services were never hit, and of course Scope cannot pickup a connection that isn't there.

The sad part is that the bug was already fixed in the codebase, but the k8s manifests were running an old version of the front-end image, which still had the bug. Hopefully these kind of occurrences can be minimised once we use flux in the k8s deployment.

Once I updated the front-end image all the connections show up:
![screen shot 2017-01-09 at 18 32 13](https://cloud.githubusercontent.com/assets/588327/21775127/9c9532c6-d69d-11e6-8d2b-ce637d7fa0c3.png)

**Closed as completed by nustiueudinastea** 2017-01-09 16:58 UTC
Labels: bug

**Comment by rade** [comment] 2017-01-09 17:04
Do any of the other deploys have hard-coded version numbers?

**Comment by nustiueudinastea** [comment] 2017-01-09 17:08
No they don't. I think k8s is the only one with versioning. From what I understand flux requires the versions. Is that true?

**Comment by rade** [comment] 2017-01-09 17:19
>  From what I understand flux requires the versions. Is that true?

Not sure. Perhaps it would be happy with ":latest"? @paulbellamy?

How do we expect users to employ flux here? Clone the repo and then point flux at it? Can't be as simple as that surely, since in order to make any changes (not much point using flux otherwise) they have to push images somewhere they have permissions to. At which point they'd need to edit the manifests anyway.

So perhaps flux is a red herring here.

**Comment by paulbellamy** [comment] 2017-01-09 17:35
> From what I understand flux requires the versions. Is that true?

Yes.

**Comment by nustiueudinastea** [comment] 2017-01-10 09:47
@paulbellamy so no chance of working with the ":latest" tag?

**Comment by paulbellamy** [comment] 2017-01-10 09:56
I think `latest` will work fine. it will just deploy latest the first time, then get changed when you do a `fluxctl release ...`.
